name: edeskyclient
description: Dart client for Czech service edesky.cz API. Supports dashboards and documents querying.
version: 1.1.0
homepage: https://github.com/janstol/edeskyclient_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  http: ^0.13.0
  xml: ^5.0.2

dev_dependencies:
  lint: ^1.5.2
  path: ^1.8.0
  test: ^1.16.5
