name: edeskyclient
description: Dart client for Czech service edesky.cz API. Supports dashboards and documents querying.
version: 1.0.0
homepage: https://github.com/janstol/edeskyclient_dart
repository: https://github.com/janstol/edeskyclient_dart
author: Jan Štol <honzastol@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  collection: ^1.14.11
  http: ^0.12.0+2
  meta: ^1.1.7
  xml: ^3.5.0

dev_dependencies:
  test: ^1.9.1
