name: edeskyclient
description: Dart client for Czech service edesky.cz API. Supports dashboards and documents querying.
version: 1.0.1+1
homepage: https://github.com/janstol/edeskyclient_dart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  collection: ^1.14.11
  http: ^0.12.0+4
  meta: ^1.1.8
  xml: ^4.1.0

dev_dependencies:
  lint: ^1.1.1
  path: ^1.6.4
  test: ^1.14.2
