name: edeskyclient
description: Dart client for Czech service edesky.cz API. Supports dashboards and documents querying.
version: 1.0.2+1
homepage: https://github.com/janstol/edeskyclient_dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  collection: ^1.14.11
  http: ^0.12.1
  meta: ^1.1.8
  xml: ^4.2.0

dev_dependencies:
  lint: ^1.2.0
  path: ^1.7.0
  test: ^1.15.1
