name: edeskyclient
description: Dart client for Czech service edesky.cz API. Supports dashboards and documents querying.
version: 0.1.0
homepage: https://github.com/janstol/edeskyclient_dart
repository: https://github.com/janstol/edeskyclient_dart
author: Jan Štol <honzastol@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0+1
  xml: ^3.4.1
  meta: ^1.0.5

dev_dependencies:
  pedantic: ^1.5.0
  test: ^1.5.3
